### PR TITLE
Add async support to custom resolvers.

### PR DESCRIPTION
**Pull request by mhemrg**
Relates to #92 
Now you can return promises from custom resolvers.
- also tests are updated to use promises.

### CODE REVIEW

**Comment by manast** [comment]
Looks great, thanks!

**Comment by djMax** [comment]
Pretty sure this is broken FYI. The for loop will always return after the first iteration. So the default resolver is the only one that ever runs.

**Comment by mhemrg** [comment]
@djMax Thank you for the review. Can you please reproduce the situation or explain it in more details?
As I know, all tests passed with this PR.

**Comment by ellisium** [comment]
I confirm resolvers is broken and perform only the first promise in array relatives to the loop. Should use promise.all

**Comment by manast** [comment]
yes the code was indeed broken. Thanks for the patch.

**Pull request merged**
