### PR TITLE
Update many, many dependencies

### PR DESCRIPTION
**Pull request by cchan**
The tests do pass!

### CODE REVIEW

**Comment by manast** [comment]
Lets remove iojs as well, its not passing the tests anyways...

**Comment by inf3rno** [comment]
You shall not pass! :-P @cchan apparently not all of them :-)

**Comment by cchan** [comment]
Oops that took a while, sorry. Let's see if it builds now!

**Comment by cchan** [comment]
lmao what happened O.o

**Comment by cchan** [comment]
Any idea why these two tests are failing on every build? Did one of my dependency updates break something?

    1) Should not have the host header passed to the target
    2) Should return 404 after route is unregister

**Comment by roccomuso** [comment]
+1

**Comment by kewitz** [comment]
+1

**Pull request closed without merging**
